name: multi-view-hybrid
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - mkl<2025
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - einops=0.8.1
  - pillow
  - pip
  - pip:
      - timm==0.9.12
      - huggingface-hub<1
